---
# =============================================================
# Handlers du role wazuh_manager
# =============================================================
# Notify rules :
#   - install paquet ou modif ossec.conf -> Restart wazuh-manager
#   - modification des regles            -> Reload wazuh-manager
# =============================================================

- name: Restart wazuh-manager
  ansible.builtin.service:
    name: wazuh-manager
    state: restarted

- name: Reload wazuh-manager
  ansible.builtin.command:
    cmd: /var/ossec/bin/wazuh-control reload
  changed_when: true
