---
galaxy_info:
  role_name: common
  author: Nova Syndicate IT
  description: Preparation de base pour toute VM Debian 12
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
