---
# Variables specifiques aux serveurs VLAN 20

# Ports SSH autorises depuis BASTION01 uniquement
ssh_allowed_nets:
  - "192.168.15.0/29"   # VLAN 15 Bastion

# MariaDB (DB01)
mariadb_bind_address: "192.168.20.12"
mariadb_port: 3306

# Samba AD (DC01)
samba_admin_user: "Administrator"
samba_dns_forwarder: "1.1.1.1"

# Partages FS01
samba_shares:
  - name: logistique
    path: /srv/shares/logistique
    valid_users: "@Logistique"
    write_list: "@Logistique"
  - name: commercial
    path: /srv/shares/commercial
    valid_users: "@Commerciaux"
    write_list: "@Commerciaux"
  - name: rh
    path: /srv/shares/rh
    valid_users: "@RH"
    write_list: "@RH"
  - name: direction
    path: /srv/shares/direction
    valid_users: "@Direction"
    write_list: "@Direction"
  - name: public
    path: /srv/shares/public
    valid_users: "@Users"
    write_list: ""
    read_only: true
