---
teleport_version:         "14.x"
teleport_cluster_name:    "nova-syndicate"
teleport_public_addr:     "bastion.nova-syndicate.local:443"
teleport_auth_type:       "local"
teleport_session_record:  "node"
teleport_cert_ttl:        "8h"
teleport_max_sessions:    5

teleport_allowed_users:
  - login: "admin-t0"
    roles: ["tier0-access"]
  - login: "admin-t1"
    roles: ["tier1-access"]

teleport_nodes:
  - hostname: "dc01"
    ip:       "192.168.20.10"
    labels:   {tier: "0", role: "dc"}
  - hostname: "fs01"
    ip:       "192.168.20.11"
    labels:   {tier: "1", role: "fileserver"}
  - hostname: "db01"
    ip:       "192.168.20.12"
    labels:   {tier: "1", role: "database"}
  - hostname: "app01"
    ip:       "192.168.20.13"
    labels:   {tier: "1", role: "app"}

hardening_extra_nft_rules:
  - "tcp dport 443 accept"
  - "tcp dport 3023 accept"
  - "tcp dport 3024 accept"
  - "tcp dport 3025 accept"
  - "ip saddr 192.168.20.13 tcp dport 9100 accept"

hardening_ssh_mfa_enabled: true

# Bastion SSH accessible depuis Mac admin + Tailscale (pas de ProxyJump pour lui-meme)
hardening_allowed_ssh_nets:
  - "192.168.15.0/29"    # Bastion VLAN (loopback Teleport nodes)
  - "192.168.18.0/24"    # Mac admin LAN
  - "192.168.20.0/28"    # Servers VLAN (Ansible depuis Proxmox)
  - "100.64.0.0/10"      # Tailscale CGNAT (acces distant Mac)

ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
