---
all:
  children:

    domain_controllers:
      hosts:
        dc01:
          ansible_host: 192.168.20.10
          ansible_user: ansible

    fileservers:
      hosts:
        fs01:
          ansible_host: 192.168.20.11
          ansible_user: ansible

    databases:
      hosts:
        db01:
          ansible_host: 192.168.20.12
          ansible_user: ansible

    bastions:
      hosts:
        bastion01:
          ansible_host: 192.168.15.10
          ansible_user: ansible

    app_servers:
      hosts:
        app01:
          ansible_host: 192.168.20.13
          ansible_user: ansible

    # Groupe fonctionnel pour cibler toutes les VMs
    nova_all:
      children:
        domain_controllers:
        fileservers:
        databases:
        bastions:
        app_servers:
