---
all:
  children:

    domain_controllers:
      hosts:
        dc01:
          ansible_host: 192.168.20.10

    fileservers:
      hosts:
        fs01:
          ansible_host: 192.168.20.11

    databases:
      hosts:
        db01:
          ansible_host: 192.168.20.12

    bastions:
      hosts:
        bastion01:
          ansible_host: 192.168.15.2

    app_servers:
      hosts:
        app01:
          ansible_host: 192.168.20.13

    proxies:
      hosts:
        proxy-lyon01:
          ansible_host: 192.168.20.14
        proxy_mrs01:
          ansible_host: 192.168.40.11
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyCommand='ssh -i ~/.ssh/nova_ansible_ed25519 -o StrictHostKeyChecking=no ansible@192.168.20.10 -W %h:%p'"

    backups:
      hosts:
        backup01:
          ansible_host: 192.168.50.2

    webservers:
      hosts:
        web01:
          ansible_host: 172.16.1.2

    mailservers:
      hosts:
        mail01:
          ansible_host: 172.16.1.3

    nova_all:
      children:
        domain_controllers:
        fileservers:
        databases:
        bastions:
        app_servers:
        proxies:
        backups:
        webservers:
        mailservers:
