---
samba_server_role:        "dc"
samba_dns_backend:        "SAMBA_INTERNAL"
samba_log_level:          1
samba_audit_enable:       true

krb5_ticket_lifetime:     "10h"
krb5_renew_lifetime:      "7d"
krb5_forwardable:         true

dhcp_range_start:         "192.168.30.100"
dhcp_range_end:           "192.168.30.200"
dhcp_subnet:              "192.168.30.0"
dhcp_netmask:             "255.255.255.0"
dhcp_lease_time:          86400

# nftables — ports Samba AD / DNS / DHCP
hardening_extra_nft_rules:
  - "tcp dport { 53, 88, 135, 139, 389, 445, 464, 636, 3268, 3269 } accept"
  - "udp dport { 53, 67, 68, 88, 123, 137, 138, 389, 464 } accept"
  - "ip saddr {{ nova_ip_app01 }} tcp dport 9100 accept"

# Paquets communs supplementaires (necessaires aux taches du role dc)
common_extra_packages:
  - cron
