---
- name: Installer gnupg et curl
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present
    update_cache: true

- name: Ajouter la cle GPG Wazuh
  ansible.builtin.shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh.gpg
  args:
    creates: /usr/share/keyrings/wazuh.gpg




- name: Ajouter le depot Wazuh
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
    state: present
    filename: wazuh


- name: Installer wazuh-agent
  ansible.builtin.apt:
    name: wazuh-agent=4.11.2-1
    state: present
    update_cache: true
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"

- name: Activer et demarrer wazuh-agent
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: true

- name: Configurer le manager dans ossec.conf
  ansible.builtin.replace:
    path: /var/ossec/etc/ossec.conf
    regexp: '<address>.*</address>'
    replace: '<address>{{ wazuh_manager_ip }}</address>'
  notify: Restart wazuh-agent

- name: Enregistrer l agent aupres du manager
  ansible.builtin.shell: |
    /var/ossec/bin/agent-auth -m {{ wazuh_manager_ip }} -p 1515
  args:
    creates: /var/ossec/etc/client.keys
  notify: Restart wazuh-agent

