---
- name: IPs statiques toutes VMs
  hosts: all
  become: true
  gather_facts: false
  vars:
    ip_config:
      bastion01: {addr: "192.168.15.2", mask: "255.255.255.248", gw: "192.168.15.1"}
      dc01:      {addr: "192.168.20.10", mask: "255.255.255.240", gw: "192.168.20.1"}
      fs01:      {addr: "192.168.20.11", mask: "255.255.255.240", gw: "192.168.20.1"}
      db01:      {addr: "192.168.20.12", mask: "255.255.255.240", gw: "192.168.20.1"}
      app01:     {addr: "192.168.20.13", mask: "255.255.255.240", gw: "192.168.20.1"}
      backup01:  {addr: "192.168.50.2",  mask: "255.255.255.248", gw: "192.168.50.1"}
  tasks:
    - name: Configurer interfaces
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback
          auto ens4
          iface ens4 inet static
            address {{ ip_config[inventory_hostname].addr }}
            netmask {{ ip_config[inventory_hostname].mask }}
            gateway {{ ip_config[inventory_hostname].gw }}
            dns-nameservers 8.8.8.8

    - name: Routes supplementaires DC1
      blockinfile:
        path: /etc/network/interfaces
        block: |
          up ip route add 192.168.40.0/26 via 192.168.20.1 || true
          up ip route add 10.10.0.0/24 via 192.168.20.1 || true
      when: inventory_hostname == "dc01"
